#!/usr/bin/env python3
"""Regenerate examples/buffers/generic_25ohm.ibs (self-consistent synthetic)."""

from __future__ import annotations

from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "examples" / "buffers" / "generic_25ohm.ibs"
VCC = 3.3
RON = 25.0


def main() -> None:
    vs = np.linspace(-VCC, 2 * VCC, 81)
    ipd = vs / RON
    ipu = -(vs / RON)

    def fmt_iv(v: np.ndarray, i: np.ndarray) -> str:
        return "\n".join(
            f"{vv:8.4f}    {ii:10.6f}    {ii * 0.9:10.6f}    {ii * 1.1:10.6f}"
            for vv, ii in zip(v, i)
        )

    tr = 0.5e-9
    t = np.linspace(0, 2e-9, 201)

    def ku_kd_rise(ti: float) -> tuple[float, float]:
        x = float(np.clip(ti / tr, 0, 1))
        return x, 1 - x

    def ku_kd_fall(ti: float) -> tuple[float, float]:
        x = float(np.clip(ti / tr, 0, 1))
        return 1 - x, x

    def simulate_vt(fn, rfix: float, vfix: float) -> np.ndarray:
        out = []
        for ti in t:
            ku, kd = fn(ti)
            a = (ku + kd) / RON + 1.0 / rfix
            b = ku * VCC / RON + vfix / rfix
            out.append(b / a)
        return np.asarray(out)

    fixtures = [(50.0, 0.0), (50.0, VCC)]
    rise = [simulate_vt(ku_kd_rise, rf, vf) for rf, vf in fixtures]
    fall = [simulate_vt(ku_kd_fall, rf, vf) for rf, vf in fixtures]

    def fmt_vt(tarr: np.ndarray, v: np.ndarray) -> str:
        return "\n".join(
            f"{tt:12.4e}    {vv:10.6f}    {vv:10.6f}    {vv:10.6f}"
            for tt, vv in zip(tarr, v)
        )

    zero = np.zeros_like(vs)
    text = f"""[IBIS Ver]      5.0
[File Name]    generic_25ohm.ibs
[File Rev]     1.0
[Source]       Generated by scripts/generate_generic_ibis.py
[Notes]        Ron={RON} ohm. IBIS into-buffer current convention.
[Disclaimer]   Synthetic — not a real silicon model.

[Component]    GENERIC
[Manufacturer] si-prelayout

[Pin]   signal_name      model_name
1       DQ               GENERIC_OUTPUT
2       DQ_IN            GENERIC_INPUT

[Model]        GENERIC_OUTPUT
Model_type     Output
Polarity       Non-Inverting
C_comp         2.0pF    1.5pF    2.5pF
[Voltage Range] 3.3      3.0      3.6

[Pulldown]
{fmt_iv(vs, ipd)}

[Pullup]
{fmt_iv(vs, ipu)}

[Gnd Clamp]
{fmt_iv(vs, zero)}

[Power Clamp]
{fmt_iv(vs, zero)}
"""
    for (rf, vf), wave in zip(fixtures, rise):
        text += f"""
[Rising Waveform]
R_fixture      {rf}
V_fixture      {vf}
{fmt_vt(t, wave)}
"""
    for (rf, vf), wave in zip(fixtures, fall):
        text += f"""
[Falling Waveform]
R_fixture      {rf}
V_fixture      {vf}
{fmt_vt(t, wave)}
"""
    text += f"""
[Ramp]
dV/dt_r        2.0/0.4n    1.5/0.5n    2.5/0.3n
dV/dt_f        2.0/0.4n    1.5/0.5n    2.5/0.3n
R_load         50

[Model]        GENERIC_INPUT
Model_type     Input
C_comp         1.5pF    1.0pF    2.0pF
[Voltage Range] 3.3      3.0      3.6

[Gnd Clamp]
{fmt_iv(vs, zero)}

[Power Clamp]
{fmt_iv(vs, zero)}

[End]
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
